# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.filename.outputs.test }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Find filename
      id: filename
      run: echo "::set-output name=test::$(ls -1 *.xml)"

  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Publish
      run: echo Filename=${{needs.build.outputs.filename}}
