# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.build.outputs.test }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: echo "::set-output name=test::hello"

  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: ECHO
      run: echo AAA= ${{needs.build.outputs.output1}}
